/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ua.uznu.vargha;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import ua.uznu.vargha.pdfjob.CreateStatniy;

/**
 *
 * @author 89502
 */
public class createStFrm extends javax.swing.JFrame {

    private static createStFrm obj = null;
    private static final int SAVESELECTOR = 3;

    /**
     * Creates new form createStFrm
     */
    public createStFrm() {
        initComponents();
        super.setIconImage(new ImageIcon(getClass().getResource("/ua/uznu/vargha/abacus.png")).getImage());
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd.MM.yyyy");
        LocalDate localDate = LocalDate.now();
        dateTxt.setText(dtf.format(localDate));
        nazvaTxt.setText(CreateStatniy.nazvaUstanovy);
    }

    public static createStFrm getInstance() {
        if (obj == null) {
            obj = new createStFrm();
        }
        return obj;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nazvaTxt = new javax.swing.JTextField();
        dateTxt = new javax.swing.JTextField();
        cancleBtn = new javax.swing.JButton();
        okBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 2));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Назва установи");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Дата");

        nazvaTxt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        dateTxt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        cancleBtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cancleBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ua/uznu/vargha/cancel.png"))); // NOI18N
        cancleBtn.setText("Назад");
        cancleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancleBtnActionPerformed(evt);
            }
        });

        okBtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        okBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ua/uznu/vargha/ok.png"))); // NOI18N
        okBtn.setText("Далі");
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cancleBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                        .addComponent(okBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(36, 36, 36)
                        .addComponent(nazvaTxt))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(100, 100, 100)
                        .addComponent(dateTxt)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nazvaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cancleBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(okBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 130));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancleBtnActionPerformed
        super.dispose();
    }//GEN-LAST:event_cancleBtnActionPerformed

    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        if (!nazvaTxt.getText().trim().equals("") && nazvaTxt.getText().trim().length() > 5
                && isDate(dateTxt.getText())) {
            CreateStatniy.nazvaUstanovy = nazvaTxt.getText();
            CreateStatniy.DATE = dateTxt.getText();
            CreateStatniy sPDF = new CreateStatniy();
            PagePrintPreviewFrame.getInstance(sPDF.create()).setVisible(true);
            PagePrintPreviewFrame.SAVESELECTOR = SAVESELECTOR;
            PagePrintPreviewFrame.menuSave.setVisible(true);
            super.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Помилка у форматі!", "Помилка", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_okBtnActionPerformed
    /**
     * Перевірка на формат дату
     *
     * @param str дата
     * @return логічний
     */
    private boolean isDate(String str) {
        SimpleDateFormat df = new SimpleDateFormat("dd.MM.yyyy");
        try {
            df.parse(str);
            return true;
        } catch (ParseException e) {
            return false;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancleBtn;
    private javax.swing.JTextField dateTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nazvaTxt;
    private javax.swing.JButton okBtn;
    // End of variables declaration//GEN-END:variables
}
