/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ua.uznu.vargha;

import java.util.Calendar;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static ua.uznu.vargha.VidomistForm.isDouble;
import static ua.uznu.vargha.VidomistForm.isLong;
import ua.uznu.vargha.pdfjob.CreateOneDFPDF;

/**
 *
 * @author 89502
 */
public class OneDFForm extends javax.swing.JFrame {

    private static OneDFForm obj = null;
    private static final int SAVESELECTOR = 2;
    private static int[] DATE = new int[2];

    /**
     * Creates new form OneDFForm
     */
    private OneDFForm() {
        initComponents();
        super.setIconImage(new ImageIcon(getClass().getResource("/ua/uznu/vargha/abacus.png")).getImage());
        for (int i = 101; i < 186; i++) {
            oznakaCombo.addItem("" + i);
        }

        Date date = new Date();
        Calendar cal = Calendar.getInstance();
        cal.setTime(date);

        DATE[0] = cal.get(Calendar.MONTH);
        DATE[1] = cal.get(Calendar.YEAR);
        OneDFSettings.getInstance();
        if (DATE[0] < 3) {
            OneDFSettings.kvartalList.setSelectedIndex(0);
        } else if (DATE[0] < 6) {
            OneDFSettings.kvartalList.setSelectedIndex(1);
        } else if (DATE[0] < 9) {
            OneDFSettings.kvartalList.setSelectedIndex(2);
        } else {
            OneDFSettings.kvartalList.setSelectedIndex(3);
        }

        OneDFSettings.rikList.setSelectedItem("" + DATE[1]);

        CreateOneDFPDF.DATE[0] = OneDFSettings.kvartalList.getSelectedItem().toString();
        CreateOneDFPDF.DATE[1] = OneDFSettings.rikList.getSelectedItem().toString();

    }

    public static OneDFForm getInstance() {
        if (obj == null) {
            obj = new OneDFForm();
        }
        return obj;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        oneDFTbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idenTxt = new javax.swing.JTextField();
        sumTxt = new javax.swing.JTextField();
        oznakaCombo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        delAllBtn = new javax.swing.JButton();
        delBtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        settingsMenu = new javax.swing.JMenu();
        toPDFMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Податковий розрахунок");
        setResizable(false);

        oneDFTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Податковий №", "Сума нарахованого доходу", "Сума виплаченого доходу", "Утримано (нараховано)", "Утримано (перераховано)", "Ознака доходу"
            }
        ));
        oneDFTbl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(oneDFTbl);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Ідентифікаційний код");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Сума нарахованого доходу");

        idenTxt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        sumTxt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        oznakaCombo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Ознака доходу");

        addBtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ua/uznu/vargha/add.png"))); // NOI18N
        addBtn.setText("Додати");
        addBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        delAllBtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        delAllBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ua/uznu/vargha/cancel.png"))); // NOI18N
        delAllBtn.setText("Видалити всі");
        delAllBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delAllBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delAllBtnActionPerformed(evt);
            }
        });

        delBtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        delBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ua/uznu/vargha/cancel.png"))); // NOI18N
        delBtn.setText("Видалити");
        delBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });

        settingsMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ua/uznu/vargha/settings.png"))); // NOI18N
        settingsMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        settingsMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(settingsMenu);

        toPDFMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ua/uznu/vargha/pdf.png"))); // NOI18N
        toPDFMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        toPDFMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toPDFMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(toPDFMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(idenTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sumTxt)
                            .addComponent(oznakaCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(62, 62, 62)
                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addComponent(delBtn)
                .addGap(97, 97, 97)
                .addComponent(delAllBtn)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(idenTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(sumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(oznakaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addBtn)
                        .addComponent(delAllBtn)
                        .addComponent(delBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        if (oneDFTbl.getRowCount() < 51) {
            if (checkCorrect()) {
                if (!VidomistForm.isContain(OneDFObj.idenList, Long.parseLong(idenTxt.getText()))) {
                    OneDFObj.addObj(Long.parseLong(idenTxt.getText()), Double.parseDouble(sumTxt.getText()), Integer.parseInt(oznakaCombo.getSelectedItem().toString()));
                    load();
                } else {
                    JOptionPane.showMessageDialog(null, "Ідентифікаційний код \nне може повторюватися!", "Помилка", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Не вдалося додати!", "Помилка", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Максимальна кількість рядків - 50!", "Помилка", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
        int index = oneDFTbl.getSelectedRow();
        if (index >= 0) {
            OneDFObj.idenList.remove(index);
            OneDFObj.sumhDohodList.remove(index);
            OneDFObj.sumUtrymane.remove(index);
            OneDFObj.oznakaList.remove(index);
            load();
        } else {
            JOptionPane.showMessageDialog(null, "Виберіть рядок!", "Інформація", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_delBtnActionPerformed

    private void delAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delAllBtnActionPerformed
        DefaultTableModel model = (DefaultTableModel) oneDFTbl.getModel();
        model.setRowCount(0);
        OneDFObj.idenList.clear();
        OneDFObj.sumhDohodList.clear();
        OneDFObj.sumUtrymane.clear();
        OneDFObj.oznakaList.clear();
        load();
    }//GEN-LAST:event_delAllBtnActionPerformed

    private void toPDFMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toPDFMenuMouseClicked
        CreateOneDFPDF df = new CreateOneDFPDF();
        PagePrintPreviewFrame.getInstance(df.create()).setVisible(true);
        PagePrintPreviewFrame.SAVESELECTOR = SAVESELECTOR;
        PagePrintPreviewFrame.menuSave.setVisible(true);
    }//GEN-LAST:event_toPDFMenuMouseClicked

    private void settingsMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsMenuMouseClicked
        OneDFSettings.getInstance().setVisible(true);
    }//GEN-LAST:event_settingsMenuMouseClicked
    /**
     * Завантаження даних в таблицю
     */
    private void load() {
        DefaultTableModel model = (DefaultTableModel) oneDFTbl.getModel();
        model.setRowCount(0);
        for (int i = 0; i < OneDFObj.idenList.size(); i++) {
            model.addRow(new Object[]{
                OneDFObj.idenList.get(i),
                OneDFObj.sumhDohodList.get(i),
                OneDFObj.sumhDohodList.get(i),
                OneDFObj.sumUtrymane.get(i),
                OneDFObj.sumUtrymane.get(i),
                OneDFObj.oznakaList.get(i)
            });
        }

    }

    /**
     * Перевірка правильністю введених даних
     *
     * @return логічний
     */
    private boolean checkCorrect() {
        if (idenTxt.getText().length() == 10
                && isLong(idenTxt.getText()) && isDouble(sumTxt.getText())) {
            return true;
        }
        return false;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton delAllBtn;
    private javax.swing.JButton delBtn;
    private javax.swing.JTextField idenTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable oneDFTbl;
    private javax.swing.JComboBox<String> oznakaCombo;
    private javax.swing.JMenu settingsMenu;
    private javax.swing.JTextField sumTxt;
    private javax.swing.JMenu toPDFMenu;
    // End of variables declaration//GEN-END:variables
}
