/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ua.uznu.vargha;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 89502
 */
public class RangSettings extends javax.swing.JFrame {

    private static RangSettings obj = null;
    private int[] index = new int[16];
    private int selectedRow = 0;

    /**
     * Creates new form StatniySettings
     */
    private RangSettings() {
        initComponents();
        super.setIconImage(new ImageIcon(getClass().getResource("/ua/uznu/vargha/abacus.png")).getImage());
        load();
    }

    public static RangSettings getInstance() {
        if (obj == null) {
            obj = new RangSettings();
        }
        return obj;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rangTbl = new javax.swing.JTable();
        rangTxt = new javax.swing.JTextField();
        nadbavkaTxt = new javax.swing.JTextField();
        UpdateBtn = new javax.swing.JButton();
        okBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 2, true));

        rangTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ранг", "Надбавка грн"
            }
        ));
        rangTbl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        rangTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rangTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(rangTbl);

        rangTxt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        nadbavkaTxt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        UpdateBtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        UpdateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ua/uznu/vargha/edit.png"))); // NOI18N
        UpdateBtn.setText("Змінити");
        UpdateBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });

        okBtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        okBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ua/uznu/vargha/ok.png"))); // NOI18N
        okBtn.setText("Готово");
        okBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Ранг");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Надбавка грн");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(UpdateBtn)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(okBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nadbavkaTxt)
                    .addComponent(rangTxt))
                .addGap(21, 21, 21))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rangTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nadbavkaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateBtn)
                    .addComponent(okBtn))
                .addGap(10, 10, 10))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 240));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
        if (!rangTxt.getText().trim().equals("") && VidomistForm.isDouble(nadbavkaTxt.getText())) {
            ConnectDB.UpdateSettings("UPDATE`rang` set `rang` = '" + rangTxt.getText() + "', `rang_hrn` = '" + nadbavkaTxt.getText() + "'  where `id` = '" + index[selectedRow] + "'");
            load();
            JOptionPane.showMessageDialog(null, "Успішно змінено!");
        } else {
            JOptionPane.showMessageDialog(null, "Помилка у форматі!", "Помилка", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_UpdateBtnActionPerformed

    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        super.dispose();
    }//GEN-LAST:event_okBtnActionPerformed

    private void rangTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rangTblMouseClicked

        if (rangTbl.getSelectedRow() >= 0) {
            selectedRow = rangTbl.getSelectedRow();
            DBSettingsObj DBobj = ConnectDB.SelectFromDBSettings("rang", index[selectedRow]);
            rangTxt.setText(DBobj.getRang());
            nadbavkaTxt.setText("" + DBobj.getRang_hrn());
        } else {
        }
    }//GEN-LAST:event_rangTblMouseClicked
    /**
     * Завантаження даних в таблицю
     */
    private void load() {
        ConnectDB.SelectFromDBSettings("SELECT * FROM rang");
        DefaultTableModel model = (DefaultTableModel) rangTbl.getModel();
        model.setRowCount(0);
        for (int i = 0; i < DBSettingsObj.getSize(); i++) {
            index[i] = DBSettingsObj.getCol1(i);
            model.addRow(new Object[]{
                DBSettingsObj.getCol2(i),
                DBSettingsObj.getCol3(i)
            });
            rangTxt.setEnabled(false);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nadbavkaTxt;
    private javax.swing.JButton okBtn;
    private javax.swing.JTable rangTbl;
    private javax.swing.JTextField rangTxt;
    // End of variables declaration//GEN-END:variables
}
