/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ua.uznu.vargha;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static ua.uznu.vargha.VidomistForm.isDouble;

/**
 *
 * @author 89502
 */
public class StatniyFrame extends javax.swing.JFrame {

    private static StatniyFrame obj = null;

    /**
     * Creates new form StatniyFrame
     */
    private StatniyFrame() {
        initComponents();
        super.setIconImage(new ImageIcon(getClass().getResource("/ua/uznu/vargha/abacus.png")).getImage());
        ConnectDB.SelectFromDBSettings("SELECT * FROM posada");
        for (int i = 0; i < DBSettingsObj.getSize(); i++) {
            posadaTxt.addItem(DBSettingsObj.getCol2(i));
        }
        ConnectDB.SelectFromDBSettings("SELECT * FROM rang");
        for (int i = 0; i < DBSettingsObj.getSize(); i++) {
            rangTxt.addItem(DBSettingsObj.getCol2(i));
        }
        ConnectDB.SelectFromDBSettings("SELECT * FROM visluha");
        for (int i = 0; i < DBSettingsObj.getSize(); i++) {
            visluhaTxt.addItem(DBSettingsObj.getCol2(i));
        }
        stavkaTXt.setText("1");
    }

    public static StatniyFrame getInstance() {
        if (obj == null) {
            obj = new StatniyFrame();
        }
        return obj;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        statniTable = new javax.swing.JTable();
        addBtn = new javax.swing.JButton();
        delBtn = new javax.swing.JButton();
        delAllBtn = new javax.swing.JButton();
        posadaTxt = new javax.swing.JComboBox<>();
        rangTxt = new javax.swing.JComboBox<>();
        visluhaTxt = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        stavkaTXt = new javax.swing.JTextField();
        mainMenu = new javax.swing.JMenuBar();
        settingsMenu = new javax.swing.JMenu();
        menuVisluha = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuPosada = new javax.swing.JMenuItem();
        createPDF = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Штатний розпис");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(120, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(120, 0));

        statniTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Назва посад", "Оклад", "Ранг", "Вислуга", "Фонд місячний"
            }
        ));
        statniTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(statniTable);

        addBtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ua/uznu/vargha/add.png"))); // NOI18N
        addBtn.setText("Додати");
        addBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addBtn.setMaximumSize(new java.awt.Dimension(120, 0));
        addBtn.setMinimumSize(new java.awt.Dimension(120, 0));
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        delBtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        delBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ua/uznu/vargha/cancel.png"))); // NOI18N
        delBtn.setText("Видалити");
        delBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delBtn.setMaximumSize(new java.awt.Dimension(120, 0));
        delBtn.setMinimumSize(new java.awt.Dimension(120, 0));
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });

        delAllBtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        delAllBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ua/uznu/vargha/cancel.png"))); // NOI18N
        delAllBtn.setText("Видалити всі");
        delAllBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delAllBtn.setMaximumSize(new java.awt.Dimension(120, 0));
        delAllBtn.setMinimumSize(new java.awt.Dimension(120, 0));
        delAllBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delAllBtnActionPerformed(evt);
            }
        });

        posadaTxt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        rangTxt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        visluhaTxt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Посада");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Ставка");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Ранг");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Вислуга");

        stavkaTXt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(posadaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(stavkaTXt)
                                            .addComponent(rangTxt, 0, 81, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(visluhaTxt, 0, 180, Short.MAX_VALUE)
                                        .addGap(69, 69, 69)))
                                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(89, 89, 89)
                .addComponent(delBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(delAllBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(posadaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(stavkaTXt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rangTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(visluhaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delAllBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 290));

        settingsMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ua/uznu/vargha/settings.png"))); // NOI18N
        settingsMenu.setToolTipText("Налаштування");
        settingsMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuVisluha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ua/uznu/vargha/star.png"))); // NOI18N
        menuVisluha.setText("Ранг");
        menuVisluha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVisluhaActionPerformed(evt);
            }
        });
        settingsMenu.add(menuVisluha);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ua/uznu/vargha/senior.png"))); // NOI18N
        jMenuItem2.setText("Вислуга");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        settingsMenu.add(jMenuItem2);

        menuPosada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ua/uznu/vargha/coin.png"))); // NOI18N
        menuPosada.setText("Посада");
        menuPosada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPosadaActionPerformed(evt);
            }
        });
        settingsMenu.add(menuPosada);

        mainMenu.add(settingsMenu);

        createPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ua/uznu/vargha/pdf.png"))); // NOI18N
        createPDF.setToolTipText("Створити pdf файл");
        createPDF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createPDF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createPDFMouseClicked(evt);
            }
        });
        mainMenu.add(createPDF);

        setJMenuBar(mainMenu);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void createPDFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createPDFMouseClicked
        createStFrm.getInstance().setVisible(true);

    }//GEN-LAST:event_createPDFMouseClicked

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        if (statniTable.getRowCount() < 21) {
            if (checkCorrect()) {
                if (!VidomistForm.isContain(StatniyObj.nazvPosadList, posadaTxt.getSelectedItem().toString())) {
                    StatniyObj.addObj(posadaTxt.getSelectedItem().toString(), Double.parseDouble(stavkaTXt.getText()),
                            rangTxt.getSelectedItem().toString(), visluhaTxt.getSelectedItem().toString());
                    load();
                } else {
                    JOptionPane.showMessageDialog(null, "Посада не може повторюватися!", "Помилка", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Не вдалося додати", "Помилка", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Максимальна кількість рядків - 20!", "Помилка", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
        int index = statniTable.getSelectedRow();
        if (index >= 0) {
            StatniyObj.remove(index);
            load();
        } else {
            JOptionPane.showMessageDialog(null, "Виберіть рядок!", "Інформація", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_delBtnActionPerformed

    private void delAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delAllBtnActionPerformed
        DefaultTableModel model = (DefaultTableModel) statniTable.getModel();
        model.setRowCount(0);
        StatniyObj.clear();
        load();
    }//GEN-LAST:event_delAllBtnActionPerformed

    private void menuVisluhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVisluhaActionPerformed
        RangSettings.getInstance().setVisible(true);
    }//GEN-LAST:event_menuVisluhaActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        VisluhaSettings.getInstance().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void menuPosadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPosadaActionPerformed
        PosadaSettings.getInstance().setVisible(true);
    }//GEN-LAST:event_menuPosadaActionPerformed
    /**
     * Завантаження даних в таблицю
     */
    private void load() {
        DefaultTableModel model = (DefaultTableModel) statniTable.getModel();
        model.setRowCount(0);
        for (int i = 0; i < StatniyObj.nazvPosadList.size(); i++) {
            model.addRow(new Object[]{
                StatniyObj.nazvPosadList.get(i),
                StatniyObj.posOkladList.get(i),
                StatniyObj.rangHRNLIst.get(i),
                StatniyObj.vislHRNLIst.get(i),
                StatniyObj.fondZPList.get(i),});
        }

    }

    private boolean checkCorrect() {
        if (isDouble(stavkaTXt.getText())) {
            return true;
        }
        return false;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JMenu createPDF;
    private javax.swing.JButton delAllBtn;
    private javax.swing.JButton delBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuBar mainMenu;
    private javax.swing.JMenuItem menuPosada;
    private javax.swing.JMenuItem menuVisluha;
    private javax.swing.JComboBox<String> posadaTxt;
    private javax.swing.JComboBox<String> rangTxt;
    private javax.swing.JMenu settingsMenu;
    private javax.swing.JTable statniTable;
    private javax.swing.JTextField stavkaTXt;
    private javax.swing.JComboBox<String> visluhaTxt;
    // End of variables declaration//GEN-END:variables
}
