/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ua.uznu.vargha;

import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ua.uznu.vargha.pdfjob.CreateVidomistPDF;

/**
 *
 * @author 89502
 */
public class VidomistForm extends javax.swing.JFrame {

    private static VidomistForm obj = null;
    private static final int SAVESELECTOR = 1;
    private static int[] DATE = new int[2];

    /**
     * Creates new form VidomistForm
     */
    private VidomistForm() {
        initComponents();
        super.setIconImage(new ImageIcon(getClass().getResource("/ua/uznu/vargha/abacus.png")).getImage());
        Date date = new Date();
        Calendar cal = Calendar.getInstance();
        cal.setTime(date);
        DATE[0] = cal.get(Calendar.MONTH);
        DATE[1] = cal.get(Calendar.YEAR);
        VidomistSettings.getInstance();
        VidomistSettings.misyacList.setSelectedIndex(DATE[0]);
        VidomistSettings.rikList.setSelectedItem("" + DATE[1]);

        CreateVidomistPDF.DATE[0] = VidomistSettings.misyacList.getSelectedItem().toString();
        CreateVidomistPDF.DATE[1] = VidomistSettings.rikList.getSelectedItem().toString();
    }

    public static VidomistForm getInstance() {
        if (obj == null) {
            obj = new VidomistForm();
        }
        return obj;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pibTxt = new javax.swing.JTextField();
        idenTxt = new javax.swing.JTextField();
        narahTxt = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        delBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        vidomTbl = new javax.swing.JTable();
        cleanBtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        settings = new javax.swing.JMenu();
        createPDF = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Відомість з. п.");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("ПІБ");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Ідентифікаційний код");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Нарахування грн");

        pibTxt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        pibTxt.setToolTipText("Прізвище Ім'я Побатькови");

        idenTxt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        idenTxt.setToolTipText("Ідентифікаційний код");

        narahTxt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        narahTxt.setToolTipText("Нарахування заробітної плати");

        addBtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ua/uznu/vargha/add.png"))); // NOI18N
        addBtn.setText("Додати");
        addBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        delBtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        delBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ua/uznu/vargha/cancel.png"))); // NOI18N
        delBtn.setText("Видалити");
        delBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });

        vidomTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ПІБ", "Іден. №", "Нарахування", "ПДВ", "Військ. збір", "Профспілка"
            }
        ));
        vidomTbl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(vidomTbl);

        cleanBtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cleanBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ua/uznu/vargha/cancel.png"))); // NOI18N
        cleanBtn.setText("Видалити всі");
        cleanBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cleanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanBtnActionPerformed(evt);
            }
        });

        settings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ua/uznu/vargha/settings.png"))); // NOI18N
        settings.setToolTipText("Налаштування");
        settings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsMouseClicked(evt);
            }
        });
        jMenuBar1.add(settings);

        createPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ua/uznu/vargha/pdf.png"))); // NOI18N
        createPDF.setToolTipText("Створити звіт");
        createPDF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createPDF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createPDFMouseClicked(evt);
            }
        });
        jMenuBar1.add(createPDF);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(narahTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pibTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idenTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99)
                .addComponent(delBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cleanBtn)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 886, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(pibTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idenTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(narahTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBtn)
                    .addComponent(delBtn)
                    .addComponent(cleanBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        if (vidomTbl.getRowCount() < 36) {
            if (checkCorrect()) {
                if (!isContain(VidomistObj.idList, Long.parseLong(idenTxt.getText()))) {
                    VidomistObj.addObj(pibTxt.getText(), Long.parseLong(idenTxt.getText()), Double.parseDouble(narahTxt.getText()));
                    load();
                } else {
                    JOptionPane.showMessageDialog(null, "Ідентифікаційний код \nне може повторюватися!", "Помилка", JOptionPane.ERROR_MESSAGE);
                }

            } else {
                JOptionPane.showMessageDialog(null, "Не вдалося додати!", "Помилка", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Максимальна кількість рядків - 35!", "Помилка", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
        int index = vidomTbl.getSelectedRow();
        if (index >= 0) {
            VidomistObj.nameList.remove(index);
            VidomistObj.idList.remove(index);
            VidomistObj.narahList.remove(index);
            VidomistObj.podatokList.remove(index);
            VidomistObj.vPodatokList.remove(index);
            VidomistObj.profSpList.remove(index);
            VidomistObj.vsohoList.remove(index);
            load();
        } else {
            JOptionPane.showMessageDialog(null, "Виберіть рядок!", "Інформація", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_delBtnActionPerformed

    private void createPDFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createPDFMouseClicked
        CreateVidomistPDF vPDF = new CreateVidomistPDF();
        PagePrintPreviewFrame.getInstance(vPDF.create()).setVisible(true);
        PagePrintPreviewFrame.SAVESELECTOR = SAVESELECTOR;
        PagePrintPreviewFrame.menuSave.setVisible(true);
    }//GEN-LAST:event_createPDFMouseClicked

    private void settingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsMouseClicked
        VidomistSettings.getInstance().setVisible(true);
    }//GEN-LAST:event_settingsMouseClicked

    private void cleanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanBtnActionPerformed
        DefaultTableModel model = (DefaultTableModel) vidomTbl.getModel();
        model.setRowCount(0);
        VidomistObj.nameList.clear();
        VidomistObj.idList.clear();
        VidomistObj.narahList.clear();
        VidomistObj.podatokList.clear();
        VidomistObj.vPodatokList.clear();
        VidomistObj.profSpList.clear();
        VidomistObj.vsohoList.clear();
        //
        load();
    }//GEN-LAST:event_cleanBtnActionPerformed
    /**
     * Завантаження даних в таблицю
     */
    private void load() {
        DefaultTableModel model = (DefaultTableModel) vidomTbl.getModel();
        model.setRowCount(0);
        for (int i = 0; i < VidomistObj.nameList.size(); i++) {
            model.addRow(new Object[]{
                VidomistObj.nameList.get(i),
                VidomistObj.idList.get(i),
                VidomistObj.narahList.get(i),
                VidomistObj.podatokList.get(i),
                VidomistObj.vPodatokList.get(i),
                VidomistObj.profSpList.get(i)});
        }

    }

    /**
     * Перевіка на довгий число
     *
     * @param s число
     * @return логічний
     */
    public static boolean isLong(String s) {
        try {
            Long.parseLong(s);
            return true;
        } catch (Exception e) {
            return false;
        }
    }

    /**
     * Перевіка на дійсне число
     *
     * @param s число
     * @return логічний
     */
    public static boolean isDouble(String s) {
        try {
            Double.parseDouble(s);
            if (Double.parseDouble(s) >= 0) {
                return true;
            } else {
                return false;
            }
        } catch (Exception e) {
            return false;
        }
    }

    /**
     * Перевірка правільності введених даних
     *
     * @return логічний
     */
    private boolean checkCorrect() {
        if (pibTxt.getText().length() > 5 && idenTxt.getText().length() == 10
                && isLong(idenTxt.getText()) && isDouble(narahTxt.getText())) {
            return true;
        }
        return false;
    }

    /**
     * Порівняння об'єктів
     *
     * @param str1 об'єкт 1
     * @param str2 об'єкт 2
     * @return логічний
     */
    public static boolean comparison(Object str1, Object str2) {
        if (str1.equals(str2)) {
            return true;
        } else {
            return false;
        }
    }

    /**
     * Масив містить такого елемента
     *
     * @param list масив
     * @param matches елемент
     * @return логічний
     */
    public static boolean isContain(List list, Object matches) {
        for (int i = 0; i < list.size(); i++) {
            if (comparison(matches, list.get(i))) {
                return true;
            }
        }
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton cleanBtn;
    private javax.swing.JMenu createPDF;
    private javax.swing.JButton delBtn;
    private javax.swing.JTextField idenTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField narahTxt;
    private javax.swing.JTextField pibTxt;
    private javax.swing.JMenu settings;
    private javax.swing.JTable vidomTbl;
    // End of variables declaration//GEN-END:variables
}
