/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ua.uznu.vargha;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 89502
 */
public class VisluhaSettings extends javax.swing.JFrame {

    private static VisluhaSettings obj = null;
    private int[] index = new int[16];
    private int selectedRow = 0;

    /**
     * Creates new form VisluhaSettings
     */
    public VisluhaSettings() {
        initComponents();
        super.setIconImage(new ImageIcon(getClass().getResource("/ua/uznu/vargha/abacus.png")).getImage());
        load();
    }

    public static VisluhaSettings getInstance() {
        if (obj == null) {
            obj = new VisluhaSettings();
        }
        return obj;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        visluhaTbl = new javax.swing.JTable();
        updateBtn = new javax.swing.JButton();
        okBtn = new javax.swing.JButton();
        visluhaTxt = new javax.swing.JTextField();
        nadbavkaTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 2));

        visluhaTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Вислуга ", "Надбавка %"
            }
        ));
        visluhaTbl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        visluhaTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                visluhaTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(visluhaTbl);

        updateBtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        updateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ua/uznu/vargha/edit.png"))); // NOI18N
        updateBtn.setText("Змінити");
        updateBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        okBtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        okBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ua/uznu/vargha/ok.png"))); // NOI18N
        okBtn.setText("Готово");
        okBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });

        visluhaTxt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        nadbavkaTxt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Вислуга");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Надбавка");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("%");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(updateBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(okBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(nadbavkaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                .addComponent(visluhaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(visluhaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nadbavkaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateBtn)
                    .addComponent(okBtn))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 240));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        super.dispose();
    }//GEN-LAST:event_okBtnActionPerformed

    private void visluhaTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visluhaTblMouseClicked
        if (visluhaTbl.getSelectedRow() >= 0) {
            selectedRow = visluhaTbl.getSelectedRow();
            DBSettingsObj DBobj = ConnectDB.SelectFromDBSettings("visluha", index[selectedRow]);
            visluhaTxt.setText(DBobj.getRang());
            nadbavkaTxt.setText("" + DBobj.getRang_hrn());
        } else {
        }
    }//GEN-LAST:event_visluhaTblMouseClicked

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        if (!visluhaTxt.getText().trim().equals("") && visluhaTxt.getText().trim().length() > 5
                && VidomistForm.isDouble(nadbavkaTxt.getText())) {
            ConnectDB.UpdateSettings("UPDATE`visluha` set `rik` = '" + visluhaTxt.getText() + "', `vidsotki` = '" + nadbavkaTxt.getText() + "'  where `id` = '" + index[selectedRow] + "'");
            load();
            JOptionPane.showMessageDialog(null, "Успішно змінено!");
        } else {
            JOptionPane.showMessageDialog(null, "Помилка у форматі!", "Помилка", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_updateBtnActionPerformed
    /**
     * Завантаження даних в таблицю
     */
    private void load() {
        ConnectDB.SelectFromDBSettings("SELECT * FROM visluha");
        DefaultTableModel model = (DefaultTableModel) visluhaTbl.getModel();
        model.setRowCount(0);
        for (int i = 0; i < DBSettingsObj.getSize(); i++) {
            index[i] = DBSettingsObj.getCol1(i);
            model.addRow(new Object[]{
                DBSettingsObj.getCol2(i),
                DBSettingsObj.getCol3(i)
            });
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nadbavkaTxt;
    private javax.swing.JButton okBtn;
    private javax.swing.JButton updateBtn;
    private javax.swing.JTable visluhaTbl;
    private javax.swing.JTextField visluhaTxt;
    // End of variables declaration//GEN-END:variables
}
